name: vinchi_the_cringy
services:
  birthday_bot:
    container_name: birthday_bot
    build: .
    environment:
      TOKEN: ${TOKEN}
      TZ: Asia/Dhaka
    working_dir: /bot
    command: python main.py
    restart: always
    volumes:
      - .:/bo