apiVersion: apps/v1
kind: Deployment
metadata:
  name: telebot-deployment
  namespace: polygon-explore
  labels:
    app: telebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telebot
  template:
    metadata:
      labels:
        app: telebot
    spec:
      containers:
        - name: telebot
          image: polygontechxyz/birthday_bot_psc:latest
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: telebot-secret
                  key: TOKEN
      imagePullSecrets:
        - name: regcred
      
